// GENERATED by tools/gen.py from sheets/strings.json (where = loading). Edit the sheet, not this file.
window.SK_LOADING_TEXT = {"en": "The fog doesn't lift. It only grows.", "es": "La niebla no se va. Solo crece."};
