// GENERATED by tools/gen.py from sheets/*.json. Edit the sheets, not this file.
#nullable enable
using System.Collections.Generic;

namespace SilentKatamari.Converter;

/// <summary>The games this mashup joins: the host Melty installs into and starts, and the two games whose real content is read from the player's own installed copy.</summary>
public sealed record GameRow(string Id, string Name, string MeltySlug, string Role, string SteamAppid, string Installdir, string ProbeFile, string Engine, string Brings, string MissingText, string Never);

public static class Games
{
    public static readonly GameRow gmod = new("gmod", "Garry's Mod", "garrys-mod", "primary", "4000", "GarrysMod", "garrysmod/gameinfo.txt", "Source (Lua), no loader needed", "The engine underneath (physics, rendering, input, sound), kept out of sight by the silentkatamari gamemode.", "-", "Ship files another mashup also ships (conflicts); overwrite base files (gmod.exe, garrysmod_*.vpk).");
    public static readonly GameRow ouak = new("ouak", "Once Upon A KATAMARI", "custom-once-upon-a-katamari", "secondary", "1880620", "OnceUponaKATAMARI", "OnceUponaKATAMARI_Data/StreamingAssets/aa", "Unity 6, IL2CPP, URP, Addressables bundles, CRIWARE audio", "The objects you roll up (real meshes and textures), Katamari's rules (catch size, growth rate from its object table), its roll-up sounds and its size display.", "missing_ouak", "Launch it, inject into it, touch its online KatamariBall mode or saves, or ship any of its files.");
    public static readonly GameRow sh2 = new("sh2", "SILENT HILL 2", "custom-silent-hill-2", "secondary", "2124490", "SILENT HILL 2", "SHProto/Content/Paks/SHProto-Windows.utoc", "Unreal Engine 5.1, IoStore containers, Wwise audio", "James Sunderland himself (his model, textures and animations) pushing the katamari, and the town's atmosphere: radio static, ambience and music.", "missing_sh2", "Launch it, patch or wrap its exe (it has a Steam DRM wrapper), decrypt it with a key from anywhere, or ship any of its files.");
    public static readonly IReadOnlyList<GameRow> All = new[] { gmod, ouak, sh2 };
    public static GameRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}

/// <summary>Everything the converter reads from the player's own games and where it writes it, under garrysmod/addons/silent_katamari_content/ on that PC only. Nothing here is ever shipped. 'source' names what the converter looks for; patterns are confirmed by the probe on a real install. Exact file formats: docs/CONTRACT.md.</summary>
public sealed record ExtractRow(string Id, string Game, string Kind, string Source, string Output, string UsedBy, bool Required);

public static class Extract
{
    public static readonly ExtractRow status = new("status", "gmod", "status", "result of every other row, converter version, each game's folder and Steam buildid", "data_static/silent_katamari/status.json", "content", true);
    public static readonly ExtractRow ouak_rules = new("ouak_rules", "ouak", "rule_table", "MonoInfo entries (catch size, bounding box, volume rate) in the object table ScriptableObjects", "data_static/silent_katamari/rules.json", "growth", true);
    public static readonly ExtractRow ouak_objects = new("ouak_objects", "ouak", "object_set", "for each tier: objects from the object table whose size fits, their prefab's MeshFilter meshes and main textures", "data_static/silent_katamari/objects.json", "stage", true);
    public static readonly ExtractRow ouak_core = new("ouak_core", "ouak", "object_set", "the katamari core mesh and texture the Prince rolls (prefab whose name contains 'core' or 'katamari' with a MeshFilter)", "data_static/silent_katamari/core.json", "ball", false);
    public static readonly ExtractRow ouak_hud = new("ouak_hud", "ouak", "sprite_set", "the in-game size display prefab: its sprites, colours and layout", "data_static/silent_katamari/hud.json", "hud", false);
    public static readonly ExtractRow ouak_font = new("ouak_font", "ouak", "font", "the Font asset used by the size display text", "resource/fonts/silent_katamari.ttf", "hud", false);
    public static readonly ExtractRow ouak_snd_rollup_s = new("ouak_snd_rollup_s", "ouak", "sound", "roll-up sound for small objects (CRI cue / AudioClip name containing 'maki' and the smallest size letter)", "sound/silent_katamari/ouak/rollup_s.wav", "sounds", false);
    public static readonly ExtractRow ouak_snd_rollup_m = new("ouak_snd_rollup_m", "ouak", "sound", "roll-up sound for middle-sized objects", "sound/silent_katamari/ouak/rollup_m.wav", "sounds", false);
    public static readonly ExtractRow ouak_snd_rollup_l = new("ouak_snd_rollup_l", "ouak", "sound", "roll-up sound for big objects", "sound/silent_katamari/ouak/rollup_l.wav", "sounds", false);
    public static readonly ExtractRow ouak_snd_hit = new("ouak_snd_hit", "ouak", "sound", "bump sound when hitting something too big", "sound/silent_katamari/ouak/hit.wav", "sounds", false);
    public static readonly ExtractRow ouak_snd_dash = new("ouak_snd_dash", "ouak", "sound", "dash sound", "sound/silent_katamari/ouak/dash.wav", "sounds", false);
    public static readonly ExtractRow ouak_snd_scaleup = new("ouak_snd_scaleup", "ouak", "sound", "size-up chime", "sound/silent_katamari/ouak/scaleup.wav", "sounds", false);
    public static readonly ExtractRow sh2_containers = new("sh2_containers", "sh2", "container_check", "header of every .utoc in SHProto/Content/Paks: magic, version, EIoContainerFlags (byte 80, Encrypted = 0x02), compression method names; .pak index encryption flag", "data_static/silent_katamari/status.json (sh2 section)", "content", true);
    public static readonly ExtractRow sh2_james_mesh = new("sh2_james_mesh", "sh2", "skeletal_mesh", "SkeletalMesh under /Game/Game/Characters/Humans/JamesSunderland/ (James's body; the most detailed LOD within the characters sheet budget), its skeleton and the base colour textures of its materials; compiled with the player's own GarrysMod/bin/studiomdl.exe", "models/silent_katamari/james.mdl", "james", true);
    public static readonly ExtractRow sh2_james_anims = new("sh2_james_anims", "sh2", "anim_set", "AnimSequences under /Game/Game/Characters/Humans/JamesSunderland/Animation/ matched by the anims sheet, sampled at 30 fps", "data_static/silent_katamari/james.json", "james", true);
    public static readonly ExtractRow sh2_ground_tex = new("sh2_ground_tex", "sh2", "texture", "a street asphalt or ground base colour texture of the town (Texture2D under /Game/Game/Environments/, name containing 'asphalt' or 'road')", "materials/silent_katamari/sh2/ground.png", "atmosphere", false);
    public static readonly ExtractRow sh2_snd_radio = new("sh2_snd_radio", "sh2", "sound", "the pocket radio's static (Wwise event or media whose name contains 'radio' and 'static' or 'noise')", "sound/silent_katamari/sh2/radio.wav", "sounds", false);
    public static readonly ExtractRow sh2_snd_ambience = new("sh2_snd_ambience", "sh2", "sound", "an outdoor fog ambience bed of the town (Wwise media whose name contains 'amb')", "sound/silent_katamari/sh2/ambience.wav", "sounds", false);
    public static readonly ExtractRow sh2_snd_music = new("sh2_snd_music", "sh2", "sound", "an exploration music track of the town (Wwise music media whose name contains 'mus' or 'bgm')", "sound/silent_katamari/sh2/music.wav", "sounds", false);
    public static readonly IReadOnlyList<ExtractRow> All = new[] { status, ouak_rules, ouak_objects, ouak_core, ouak_hud, ouak_font, ouak_snd_rollup_s, ouak_snd_rollup_m, ouak_snd_rollup_l, ouak_snd_hit, ouak_snd_dash, ouak_snd_scaleup, sh2_containers, sh2_james_mesh, sh2_james_anims, sh2_ground_tex, sh2_snd_radio, sh2_snd_ambience, sh2_snd_music };
    public static ExtractRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}

/// <summary>Rings of Katamari objects around the stage centre. The converter picks real objects from the player's Once Upon A KATAMARI whose own pickup size (the katamari size needed to roll it up) falls in each tier; the stage places them. Tier bounds follow the pickup sizes of Make a Star 1 (REROLL object table): about 40% of placements in the smallest tier, post-goal bait at 10-25 cm, unpickable walls from 35 cm.</summary>
public sealed record TierRow(string Id, double PickupMinCm, double PickupMaxCm, int Kinds, int Count, double RingMinM, double RingMaxM, bool Catchable, string Prefer);

public static class Tiers
{
    public static readonly TierRow t1_smallest = new("t1_smallest", 1.5, 4.5, 10, 120, 0.05, 0.7, true, "objects that fit a quiet, uneasy clearing (yokai, Edo and graveyard things) first, then any");
    public static readonly TierRow t2_tiny = new("t2_tiny", 4.5, 7.6, 8, 70, 0.2, 1.1, true, "objects that fit a quiet, uneasy clearing (yokai, Edo and graveyard things) first, then any");
    public static readonly TierRow t3_small = new("t3_small", 7.6, 10.0, 6, 40, 0.5, 1.7, true, "objects that fit a quiet, uneasy clearing (yokai, Edo and graveyard things) first, then any");
    public static readonly TierRow t4_medium = new("t4_medium", 10.0, 14.5, 6, 30, 0.9, 2.3, true, "objects that fit a quiet, uneasy clearing (yokai, Edo and graveyard things) first, then any");
    public static readonly TierRow t5_big = new("t5_big", 14.5, 25.0, 4, 14, 1.4, 2.8, true, "objects that fit a quiet, uneasy clearing (yokai, Edo and graveyard things) first, then any");
    public static readonly TierRow t6_walls = new("t6_walls", 45.0, 120.0, 3, 8, 1.0, 3.0, false, "big furniture-like things that make walls and corners");
    public static readonly IReadOnlyList<TierRow> All = new[] { t1_smallest, t2_tiny, t3_small, t4_medium, t5_big, t6_walls };
    public static TierRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}

/// <summary>Animations of the pushing character, chosen from how the katamari moves. The converter matches 'match' (case-insensitive substrings, all must appear) against the AnimSequence names under the character's folder and samples the first hit at 30 fps.</summary>
public sealed record AnimRow(string Id, string Character, IReadOnlyList<string> Match, IReadOnlyList<string> Avoid, string When, double Speed, bool Loop);

public static class Anims
{
    public static readonly AnimRow idle = new("idle", "james", new string[] { "idle" }, new string[] { "injur", "weapon", "pipe", "gun", "flashlight", "turn" }, "standing still", 1.0, true);
    public static readonly AnimRow walk = new("walk", "james", new string[] { "walk", "f" }, new string[] { "injur", "weapon", "pipe", "gun", "start", "stop", "turn", "bwd", "back" }, "pushing slowly forward", 1.0, true);
    public static readonly AnimRow run = new("run", "james", new string[] { "run", "f" }, new string[] { "injur", "weapon", "pipe", "gun", "start", "stop", "turn", "bwd", "back" }, "pushing fast or dashing", 1.0, true);
    public static readonly AnimRow walk_back = new("walk_back", "james", new string[] { "walk", "b" }, new string[] { "injur", "weapon", "pipe", "gun", "start", "stop", "turn" }, "pulling back", 1.0, true);
    public static readonly AnimRow strafe_left = new("strafe_left", "james", new string[] { "walk", "l" }, new string[] { "injur", "weapon", "pipe", "gun", "start", "stop", "turn" }, "pushing to the left", 1.0, true);
    public static readonly AnimRow strafe_right = new("strafe_right", "james", new string[] { "walk", "r" }, new string[] { "injur", "weapon", "pipe", "gun", "start", "stop", "turn" }, "pushing to the right", 1.0, true);
    public static readonly IReadOnlyList<AnimRow> All = new[] { idle, walk, run, walk_back, strafe_left, strafe_right };
    public static AnimRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}

/// <summary>Silent Hill 2 characters who push the katamari. v0.1: James Sunderland.</summary>
public sealed record CharacterRow(string Id, string Name, string Game, string Mesh, string Anims, int MaxTriangles, int MaxBones, string ArmPose, IReadOnlyList<string> Clips);

public static class Characters
{
    public static readonly CharacterRow james = new("james", "James Sunderland", "sh2", "sh2_james_mesh", "sh2_james_anims", 16000, 90, "upper arms raised forward ~70 degrees and forearms bent ~25 degrees, blended over his walk/run clips, palms on the ball", new string[] { "idle", "walk", "run", "walk_back", "strafe_left", "strafe_right" });
    public static readonly IReadOnlyList<CharacterRow> All = new[] { james };
    public static CharacterRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}

/// <summary>Stages. v0.1 has one: a clearing in the fog, at Katamari scale (James is a few cm tall), with real Katamari objects placed in rings by the size you need to roll them up. Numbers follow Katamari's first stages: Make a Star 1 (REROLL mission data: 5 cm start, 10 cm goal, 30 cm cap, ratings 10/12/14/15 cm) and Once Upon A KATAMARI's 'As Large As Possible 1' (15 cm in 4 minutes).</summary>
public sealed record StageRow(string Id, string Map, IReadOnlyList<double> Center, double StartDiameterCm, double GoalCm, IReadOnlyList<double> RatingCm, double MaxCm, int TimeS, IReadOnlyList<string> Tiers, string Ground, double GroundSizeM, string Music, string Ambience, string Radio);

public static class Stage
{
    public static readonly StageRow clearing = new("clearing", "gm_flatgrass", new double[] { 0.0, 0.0, -12288.0 }, 5.0, 15.0, new double[] { 15.0, 18.0, 21.0, 24.0 }, 45.0, 240, new string[] { "t1_smallest", "t2_tiny", "t3_small", "t4_medium", "t5_big", "t6_walls" }, "sh2_ground_tex", 12.0, "sh2.music", "sh2.ambience", "sh2.radio");
    public static readonly IReadOnlyList<StageRow> All = new[] { clearing };
    public static StageRow? ById(string id) { foreach (var r in All) if (r.Id == id) return r; return null; }
}
