"""Generate code from the design sheets. Each row becomes one Lua table (the game) and, for the sheets the
converter needs, one C# record instance. Never edit the generated files by hand.

  python3 tools/gen.py           write the generated files
  python3 tools/gen.py --check   exit 1 if the generated files are out of date (used before packaging)
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sheets import ROOT, load_all  # noqa: E402

LUA_OUT = os.path.join(ROOT, "addons", "silent_katamari", "gamemodes", "silentkatamari", "gamemode", "sk", "sh_sheets.lua")
CS_OUT = os.path.join(ROOT, "converter", "SilentKatamari.Converter", "Sheets.g.cs")
CS_SHEETS = ["games", "extract", "tiers", "anims", "characters", "stage"]
LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in",
                "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"}


def lua_str(s):
    out = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")
    return '"' + out + '"'


def lua_val(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_val(x) for x in v) + " }" if v else "{}"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{lua_key(k)} = {lua_val(x)}" for k, x in v.items()) + " }"
    if v is None:
        return "nil"
    raise TypeError(type(v))


def lua_key(k):
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k) and k not in LUA_KEYWORDS:
        return k
    return "[" + lua_str(k) + "]"


def gen_lua(sheets):
    lines = ["-- GENERATED by tools/gen.py from sheets/*.json. Edit the sheets, not this file.",
             "SK = SK or {}", "SK.Sheets = {}"]
    for name, sheet in sheets.items():
        cols = list(sheet["columns"].keys())
        lines.append(f"SK.Sheets.{name} = {{")
        for row in sheet["rows"]:
            fields = ", ".join(f"{lua_key(c)} = {lua_val(row[c])}" for c in cols if c in row)
            lines.append(f"\t[{lua_str(row['id'])}] = {{ {fields} }},")
        lines.append("}")
        order = ", ".join(lua_str(r["id"]) for r in sheet["rows"])
        lines.append(f"SK.Sheets.{name}_order = {{ {order} }}")
    lines += ["SK.Rules = {}",
              "for id, row in pairs(SK.Sheets.rules) do SK.Rules[id] = row.value end", ""]
    return "\n".join(lines)


def pascal(s):
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]+", s) if p)


def cs_ident(s):
    s = re.sub(r"[^A-Za-z0-9_]", "_", s)
    return "_" + s if s[0].isdigit() else s


def cs_type(ctype):
    if ctype.startswith("list:"):
        return f"IReadOnlyList<{cs_type(ctype[5:])}>"
    return {"number": "double", "int": "int", "bool": "bool"}.get(ctype, "string")


def cs_val(ctype, v):
    if ctype.startswith("list:"):
        inner = ctype[5:]
        return f"new {cs_type(inner)}[] {{ {', '.join(cs_val(inner, x) for x in v)} }}"
    if ctype == "number":
        return repr(float(v)) if isinstance(v, (int, float)) else "0"
    if ctype == "int":
        return str(int(v))
    if ctype == "bool":
        return "true" if v else "false"
    return json.dumps(v, ensure_ascii=False)


def gen_cs(sheets):
    out = ["// GENERATED by tools/gen.py from sheets/*.json. Edit the sheets, not this file.",
           "#nullable enable", "using System.Collections.Generic;", "",
           "namespace SilentKatamari.Converter;", ""]
    for name in CS_SHEETS:
        sheet = sheets[name]
        cols = sheet["columns"]
        rec = pascal(name).rstrip("s") + "Row" if name != "stage" else "StageRow"
        params = ", ".join(f"{cs_type(spec['type'])} {pascal(c)}" for c, spec in cols.items())
        out.append(f"/// <summary>{sheet['about']}</summary>")
        out.append(f"public sealed record {rec}({params});")
        out.append("")
        out.append(f"public static class {pascal(name)}")
        out.append("{")
        for row in sheet["rows"]:
            args = ", ".join(cs_val(spec["type"], row[c]) for c, spec in cols.items())
            out.append(f"    public static readonly {rec} {cs_ident(row['id'])} = new({args});")
        all_ids = ", ".join(cs_ident(r["id"]) for r in sheet["rows"])
        out.append(f"    public static readonly IReadOnlyList<{rec}> All = new[] {{ {all_ids} }};")
        out.append(f"    public static {rec}? ById(string id) {{ foreach (var r in All) if (r.Id == id) return r; return null; }}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def main():
    sheets = load_all()
    outputs = {LUA_OUT: gen_lua(sheets), CS_OUT: gen_cs(sheets)}
    stale = []
    for path, text in outputs.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != text:
            stale.append(os.path.relpath(path, ROOT))
            if "--check" not in sys.argv:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    if "--check" in sys.argv:
        if stale:
            print("out of date: " + ", ".join(stale))
            return 1
        print("generated files are up to date")
        return 0
    print("wrote: " + (", ".join(stale) if stale else "nothing (up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
